apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-aware-scheduler-plugin
  labels:
    app: energy-aware-scheduler-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-aware-scheduler-plugin
  template:
    metadata:
      labels:
        app: energy-aware-scheduler-plugin
    spec:
      containers:
      - name: scheduler-plugin
        image: your-docker-repo/energy-aware-scheduler-plugin:latest
        ports:
        - containerPort: 5000
        env:
        - name: NVML_ENABLED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: your-node-name
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
